// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dtypCQeDZcN-3W27gQtu5vTfNVivqvg',
    appId: '1:469690680010:web:6ffec1512843c91cb26a33',
    messagingSenderId: '469690680010',
    projectId: 'big-market-c475c',
    authDomain: 'big-market-c475c.firebaseapp.com',
    storageBucket: 'big-market-c475c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlR7V7RSUTWLhKR4sXqXK_035molhig8k',
    appId: '1:469690680010:android:894560cc5946ce87b26a33',
    messagingSenderId: '469690680010',
    projectId: 'big-market-c475c',
    storageBucket: 'big-market-c475c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPhpk_aIBC3uizRUB1cXtciuUjqiswG1M',
    appId: '1:469690680010:ios:cd0f2e59c6d8c83bb26a33',
    messagingSenderId: '469690680010',
    projectId: 'big-market-c475c',
    storageBucket: 'big-market-c475c.appspot.com',
    iosBundleId: 'com.example.bigMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPhpk_aIBC3uizRUB1cXtciuUjqiswG1M',
    appId: '1:469690680010:ios:d4d690b70894beb8b26a33',
    messagingSenderId: '469690680010',
    projectId: 'big-market-c475c',
    storageBucket: 'big-market-c475c.appspot.com',
    iosBundleId: 'com.example.bigMarket.RunnerTests',
  );
}
